version: 2.1

executors:
  dotnet-executor:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:8.0
  dotnet-node-executor:
    docker:
      - image: dotnetimages/microsoft-dotnet-core-sdk-nodejs:8.0_16.x

jobs:
  check-commit:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: |
          COMMIT_MSG=$(git log -1 --pretty=%B)
          echo "Commit message: $COMMIT_MSG"
          if echo "$COMMIT_MSG" | grep -q "\[skip ci\]"; then
            echo "Skipping due to [skip ci]"
            circleci-agent step halt
          fi
  build:
    executor: dotnet-executor
    steps:
      - checkout
      - run: dotnet restore
      - run: dotnet build --no-restore -c Release
  pack:
    executor: dotnet-node-executor
    steps:
      - checkout:
          path: .
          fetch-depth: 0
      - run: dotnet restore
      - restore_cache:
          keys:
            - node-deps-{{ checksum "SemanticRelease.Abstractions.sln" }}
            - node-deps-
      - run: |
          npm install --no-save \
            semantic-release \
            @semantic-release/commit-analyzer \
            @semantic-release/release-notes-generator \
            @semantic-release/changelog \
            @semantic-release/exec \
            @semantic-release/git \
            @semantic-release/github
      - run: npx semantic-release
      - run: dotnet build --no-restore -c Release
      - run: dotnet pack --no-build -o ./artifacts -c Release
      - persist_to_workspace:
          root: artifacts
          paths:
            - "*.nupkg"
      - save_cache:
          key: node-deps-{{ checksum "SemanticRelease.Abstractions.sln" }}
          paths: ~/.npm
  publish:
    executor: dotnet-executor
    steps:
      - attach_workspace:
          at: /artifacts
      - run:
          name: Validate presence of API Key
          command: 'echo "Key is: ${NugetAuthentication:0:4}****"'
      - run:
          name: Push to NuGet
          command: |
            dotnet nuget push "artifacts/*.nupkg" \
              --source "https://api.nuget.org/v3/index.json" \
              --api-key "$NugetAuthentication"

workflows:
  release:
    jobs:
      - check-commit:
          filters:
            branches:
              only: master
            tags:
              ignore: /.*/
      - pack:
          requires:
            - check-commit
      - publish:
          context: DeploymentKeys
          requires:
            - pack
  pr-checks:
    jobs:
      - build:
          filters:
            branches:
              ignore: /.*/   # Do not run directly on branches
            pull_requests:
              only: /.*/     # Run on all PRs